#!/bin/bash
ADDR=$(hyprctl clients -j | jq -r '.[] | select(.title == "wiremix") | .address' | head -n1)
if [[ -n $ADDR ]]; then
  hyprctl dispatch "hl.dsp.focus({ window = \"address:$ADDR\"})"
else
  hyprctl dispatch 'hl.dsp.exec_cmd("ghostty --title=wiremix -e wiremix")'
fi
