background {
    monitor    =
    path       = ~/Pictures/wallpapers/i4ulncmrre021.jpg
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.7
}

input-field {
    monitor  =
    size     = 280, 52
    halign   = center
    valign   = center
    position = 0, -80

    outline_thickness = 3
    dots_size         = 0.3
    dots_spacing      = 0.2
    dots_center       = true

    outer_color   = rgb(A0B3C9)
    inner_color   = rgba(0c191bcc)
    font_color    = rgb(c2c5c6)
    check_color   = rgb(BBD1E2)
    fail_color    = rgb(B18C81)

    placeholder_text = <i>password</i>
    fail_text        = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 10
}

# Clock
label {
    monitor  =
    halign   = center
    valign   = center
    position = 0, 80

    text     = cmd[update:1000] echo "<span font='48'>$(date +'%H:%M')</span>"
    color    = rgba(c2c5c6ff)
    font_family = monospace
}

# Date
label {
    monitor  =
    halign   = center
    valign   = center
    position = 0, 20

    text     = cmd[update:60000] echo "$(date +'%A, %B %-d')"
    color    = rgba(98A3B8cc)
    font_size   = 16
    font_family = monospace
}
