background       = 0xFF122C29
base             = 0xFF1A3431
alternate_base   = 0xFF223C39
text             = 0xFFC3CAC9
bright_text      = 0xFFDDE8E7
accent           = 0xFF3AB2DC
accent_secondary = 0xFF1A6D8E

font_family            = JetBrainsMono Nerd Font
font_family_monospace  = JetBrainsMono Nerd Font Mono

rounding_large = 10
rounding_small = 5D
